# Generated by Django 5.2.7 on 2025-12-01 15:02

from django.db import migrations

def create_profile(apps, schema_editor):
    user = apps.get_model('auth', 'User')
    Profile = apps.get_model('accounts', 'Profile')
    for user in user.objects.all():
        Profile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_profile, migrations.RunPython.noop),
    ]
