# Generated by Django 5.2.7 on 2025-11-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток'),
        ),
    ]
