# Generated by Django 5.2.7 on 2025-11-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_order_productorder_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
